// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACMedPatient: typeof import('./src/components/ACMedPatient.vue')['default']
    ACMedWard: typeof import('./src/components/ACMedWard.vue')['default']
    AdmissionDrugAllergy: typeof import('./src/components/AdmissionDrugAllergy.vue')['default']
    AdmissionHerb: typeof import('./src/components/AdmissionHerb.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BorderedBox: typeof import('./src/components/BorderedBox.vue')['default']
    ConsultBox: typeof import('./src/components/ConsultBox.vue')['default']
    ConsultTable: typeof import('./src/components/ConsultTable.vue')['default']
    HNBox: typeof import('./src/components/HNBox.vue')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    PatientIden: typeof import('./src/components/PatientIden.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VModal: typeof import('./src/components/VModal.vue')['default']
  }
}

export {}
